# Generated by Django 5.0.3 on 2024-05-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İlaç Adı')),
                ('active_ingredient', models.CharField(max_length=100, verbose_name='Etken Hastalık')),
                ('allergens', models.CharField(max_length=200, verbose_name='Alerjen Madde')),
                ('kronik_rahatsizlik', models.CharField(max_length=200, verbose_name='Kronik Rahatsızlık')),
                ('arac_kullanimi', models.BooleanField(default=False)),
                ('kullanım_suresi', models.DurationField(verbose_name='Kullanım Süresi')),
                ('kullanım_talimatı', models.CharField(max_length=200, verbose_name='Kullanım Talimatı')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Kullanıcı Adı')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('weight', models.FloatField(verbose_name='Kilo')),
                ('height', models.FloatField(verbose_name='Boy')),
                ('age', models.FloatField(verbose_name='Yaş')),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın'), ('O', 'Diğer')], max_length=1, verbose_name='Cinsiyet')),
            ],
        ),
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suggested', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
